### PR TITLE
Add revised repo format

### PR DESCRIPTION
**Pull request by mooner-the-creator**
real

### CODE REVIEW

**Comment by mooner-the-creator** [comment]
Codacy says `≤ 0 Minor issues` on the page btw

**Comment by ia74** [comment]
> Codacy says `≤ 0 Minor issues` on the page btw

i dont listen to codacy anymopre

**Comment by mooner-the-creator** [comment]
> > Codacy says `≤ 0 Minor issues` on the page btw
> 
> i dont listen to codacy anymopre

thats kinda the point, because it says it failed inside github

**Comment by mooner-the-creator** [comment]
github*

**Comment by ia74** [comment]
oh yea

**Comment by mooner-the-creator** [comment]
This is no longer required due to Manifest V3

**Comment by ia74** [comment]
oh i was about to do that

**Comment by ia74** [comment]
Fair enough

**Pull request closed without merging**
